title: Emmanuel Tublu
description: Data Scientist Junior | Analyse financière | Machine Learning

theme: jekyll-theme-cayman

author:
  name: Emmanuel Tublu
  email: tubluemmanuel61@gmail.com

github:
  username: emmanuel-tublu

show_downloads: false
