title: Emmanuel Tublu
description: Data Scientist Junior spécialisé en analyse financière et modélisation
theme: minima

author:
  name: Emmanuel Tublu
  email: tubluemmanuel61@gmail.com

header_pages:
  - index.md
  - projects.md
  - about.md

social_links:
  github: emmanuel-tublu

show_excerpts: true
