title: Emmanuel Tublu
description: Data Scientist Junior | Analyse de données | Machine Learning
theme: minima

author:
  name: Emmanuel Tublu
  email: tubluemmanuel61@gmail.com

show_excerpts: true

header_pages:
  - index.md
  - projects.md

social_links:
  github: emmanuel-tublu
